---
#- name: Show bam_tar variable
#  debug:
#    var: bam_tar
- name: Ensure "{{ base_dir }}" exists
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Unpack BAM tarball into images dir
  unarchive:
    src:   "{{ bam_tar }}"
    dest:  "{{ base_dir }}"
    remote_src: yes
    creates:    "{{ base_dir }}/{{bam_qcow}}"
  become: true

- name: Copy image to libvirt
  ansible.builtin.copy:
    src: "{{ base_dir }}/{{bam_qcow}}"
    dest: "{{ images_dir }}/{{bam_qcow}}"
    force: yes
    remote_src: yes

- name: Define the BAM domain
  community.libvirt.virt:
    name: "{{bam_name}}"
    command: define
    xml:  "{{ lookup('template', bam_xml_template) }}"
    autostart: true
  become: true

- name: Start the BAM domain
  community.libvirt.virt:
    name: "{{bam_name}}"
    state: running
  become: true

