---
#- name: Show bam_tar variable
#  debug:
#    var: bam_tar
- name: Unpack BAM tarball into images dir
  unarchive:
    src:   "{{ bam_tar }}"
    dest:  "{{ base_dir }}"
    remote_src: yes
    creates:    "{{ base_dir }}/{{bam_qcow}}"
  become: true

- name: Copy image to libvirt
  ansible.builtin.copy:
    src: "{{ base_dir }}/{{bam_qcow}}"
    dest: "{{ images_dir }}/{{bam_qcow}}"
    force: yes
    remote_src: yes

- name: Define the BAM domain
  community.libvirt.virt:
    name: proteus
    command: define
    xml:  "{{ lookup('template', 'bam-9.6.0-template.xml.j2') }}"
    autostart: true
  become: true

- name: Start the BAM domain
  community.libvirt.virt:
    name: proteus
    state: running
  become: true

