---
- name: Unpack BDDS tarball into images dir
  unarchive:
    src:   "{{ bdds_tar }}"
    dest:  "{{ base_dir }}"
    remote_src: yes
    creates:    "{{ base_dir }}/{{bdds_qcow}}"
  become: yes

- name: Copy image to libvirt
  ansible.builtin.copy:
    src: "{{ base_dir }}/{{bdds_qcow}}"
    dest: "{{ images_dir }}/{{bdds_qcow}}"
    force: yes

- name: Define the BDDS domain
  community.libvirt.virt:
    name: adonis
    command: define
    xml:  "{{ lookup('template', 'bdds-9.6.0-template.xml.j2') }}"
    autostart: true
  become: yes

- name: Start the BDDS domain
  community.libvirt.virt:
    name: adonis
    state: running
  become: yes

