---
#General jobs for all labs
- name: Configure all hosts
  hosts: local
  roles:
  - labcommon
  become: true

##Specific jobs for each labs
#- name: Configure vholab1
#  hosts: lab1
#  roles:
#  - vholab1
#  become: true
#
#- name: Configure vholab2
#  hosts: lab2
#  roles:
#  - vholab2
#  become: true
#
##General jobs for all KVMs
#- name: Configure basics kvms on labs
#  hosts:
#  - vm_lab1
#  - vm_lab2
#  roles:
#  - common
#  become: true

##Specific jobs for each KVMs
#- import_playbook: vhodocker_init.yml
#- import_playbook: vhoflask_init.yml
#
#- name: Configure vhoweb
#  hosts: vhoweb
#  become_user: root
#  become: true
#  roles:
#  - apache
#
#- name: Configure vhopi
#  hosts: vhopi
#  become_user: root
#  become: true
#  roles:
#  - pihole

