---
- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
      - vm_name: dash
      - virt_network: vhobr1-network
      - qcow2_size: 20G
