---
- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
       vm_name: otrs-k
       virt_network: vhobr3-network
       qcow2_size: 4G
       target_distro: debian
