#!/bin/bash
#in .bashrc add
#alias playlab="/home/vho/Documents/ansible-pull-docker/playlab"
#source .bashrc
current_dir=$( pwd )
playbook_dir=/home/vho/vho-database/ansible-vholab/

cd "$playbook_dir"
#git pull

sudo ansible-playbook /home/vho/vho-database/ansible-vholab/hostall_init.yml
