---
- name: Installing Znuny + backup
  hosts: otrs-p
  become: yes
  roles:
    - role: otrs
      tags: [otrs]

#ansible otrs-p -i inventory -m ping --ask-vault-pass
#ansible-playbook -i inventory play-otrs.yml --ask-vault-pass -vvv