#!/bin/bash
#in .bashrc add
#alias playbc="/home/vho/Documents/ansible-pull-docker/playbc"
#source .bashrc
current_dir=$( pwd )
playbook_dir=/home/vho/Documents/ansible-pull-docker/

cd "$playbook_dir"
#git pull

ansible-playbook /home/vho/Documents/ansible-pull-docker//bluecat_deploy.yml
