# roles/bluecat/defaults/main.yml

base_dir: /root/bluecat_dir
images_dir: /var/lib/libvirt/images
bridge_nw: vhobr3-network

bam_tar:             /root/9.5.0/bam_kvm_9.5.0-644.GA.bcn_amd64.tar.tar
bam_xml_template:    bam-template.xml.j2
bam_qcow: bam_kvm_9.5.0-644.GA.bcn_amd64.qcow2 
bam_name: proteus-rit


bdds_tar:            /root/9.5.0/bdds_kvm_9.5.0-644.GA.bcn_amd64.tar.tar
bdds_xml_template:   lookup('template', 'bdds-template.xml.j2')
bdds_qcow: bdds_kvm_9.5.0-644.GA.bcn_amd64.qcow2

src_net: "192.168.1.0/24"
dst_net: "192.168.122.0/24"
