# roles/bluecat/defaults/main.yml

images_dir: /var/lib/libvirt/images

bam_tar:             /root/9.6.0/bam_kvm_9.6.0-576.GA.bcn_amd64.tar.tar
bam_xml_template:    lookup('template', 'bam-9.6.0-template.xml.j2')
bam_xml_dest:        /etc/libvirt/qemu/bam9.6.xml

bdds_tar:            /root/9.6.0/bdds_kvm_9.6.0-576.GA.bcn_amd64.tar.tar
bdds_xml_template:   lookup('template', 'bdds-9.6.0-template.xml.j2')
bdds_xml_dest:       /etc/libvirt/qemu/bdds9.6.xml

