# setup files for bridging KVMs
- name: Update APT Cache
  apt:
    update_cache: yes
    force_apt_get: yes
 
- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Install packages
  apt:
    package:
    - cloud-image-utils
    - fail2ban
    - git
    - ansible
    - openssh-server
    - openssh-client
    - qemu-kvm
    - libvirt-daemon-system 
    - libvirt-clients 
    - bridge-utils 
- name: Copy setup bridge template
  template:
    src: "templates/br0.netdev.j2"
    dest: "{{networkfolder}}/br0.netdev"
    force: no 
    mode: 0644
- name: Copy setup bound bridge template
  template:
    src: "templates/1-vhobr-bind.network.j2"
    dest: "{{networkfolder}}/1-{{network_brd}}-bind.network"
    force: no
    mode: 0644
- name: Copy setup dhcp for bridge template
  template:
    src: "templates/2-vhobr-dhcp.network.j2"
    dest: "{{networkfolder}}/2-{{network_brd}}-dhcp.network"
    force: no 
    mode: 0644

- name: Copy template for new virtual network 
  template:
    src: "templates/vhobr-network.xml.j2"
    dest: "{{rootfolder}}/{{virt_network}}.xml"
    force: no
    mode: 0644

- name: Define the virtual network in libvirt
  command: >
    virsh net-define {{ rootfolder }}/{{ virt_network }}.xml
  args:
    creates: "/etc/libvirt/qemu/networks/{{ virt_network }}.xml"

- name: Set the virtual network to autostart
  command: >
    virsh net-autostart {{ virt_network }}

- name: Start the virtual network
  command: >
    virsh net-start {{ virt_network }}


- name: Enable systemd-networkd
  command: |
    systemctl enable systemd-networkd

- name: Start systemd-networkd
  command: |
    systemctl start systemd-networkd

- name: Restart systemd-timesyncd
  command: |
    systemctl restart systemd-timesyncd.service

- name: Disable NetworkManager-wait-online.service
  command: |
    systemctl disable NetworkManager-wait-online.service
