#FROM debian:10
#FROM debian:11-slim

LABEL	maintainer="dispelk9@gmail.com"

RUN apt update && apt upgrade

RUN apt install sudo locales --yes 

RUN apt install -y python3 python3-pip git ansible

#for debian11
#RUN apt install -y cron
    

#for debian 11    
#   pip3 install "Jinja2<3.1"

