#FROM debian:10
#FROM debian:11-slim
FROM httpd:2.4

LABEL	maintainer="dispelk9@gmail.com"

# For debian test
# RUN apt update && apt upgrade
# RUN apt install sudo locales --yes 
# RUN apt install -y python3 python3-pip git ansible

COPY ./Paladium/ /usr/local/apache2/htdocs/

